### GET request to example server
PUT http://localhost:1012/meeting/695ec7e2d397571ae57c60f9
Content-Type: application/json

{
  "date": "2026-02-03T00:00:00Z",
  "startTime": "2026-02-03T10:00:00Z",
  "endTime": "2026-02-03T10:30:00Z",
  "status": "CONFIRMED"
}

###