### GET request to example server
PUT http://localhost:1012/meeting/6962cc086137a97da0090275
Content-Type: application/json

{
  "date": "2026-02-05T00:00:00Z",
  "startTime": "2026-02-05T10:00:00Z",
  "endTime": "2026-02-05T10:30:00Z",
  "status": "CONFIRMED"
}

###