package org.com.meetingservice.additional;

public enum Specialization {

    CARDIOLOGIST,
    DERMATOLOGIST,
    OPHTHALMOLOGIST,
    DENTIST,
    NEUROLOGIST,
    ORTHOPEDIC,
    GASTROENTEROLOGIST,
    SURGEON,
    PEDIATRICIAN,
    NEPHROLOGIST,
    ONCOLOGIST,
    PULMONOLOGIST,
    GYNAECOLOGIST,
    HEPATOLOGIST,
    PSYCHIATRIST
}
